version: "3"
services:
  client:
    build: .
    environment:
      - NODE_ENV=development
    volumes:
      - .:/client
    command: sh -c 'cd client && yarn start'
    ports:
      - "3000:3000"
    tty: true